#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=99
STOP=99
 
start() {        
        echo start
        /usr/share/bamfa-remote/bamfa-remote -c /usr/share/bamfa-remote/config.yaml
}                 
 
stop() {          
        echo stop
        killall bamfa-remote
}
